### ISSUE TITLE
Just doesn't work at all

### ISSUE THREAD

**Issue by SLinxTheFox** [Xruptor/LootRollMover#3]
no matter where i move the anchor it makes no difference, even if i turn off the skin in elvui. it jsut defaults to upper left

**Comment by Xruptor** [comment]
Interesting, this is the first I've heard of this.  Quite a number of folks use my addon even with the Shadowlands pre-patch.  I'll have to investigate this a bit more.  Could you provide me with some details as to what addons you use and if you are playing on classic or retail servers?

**Comment by Xruptor** [comment]
One quick thing that came to mind.  If you have ElvUI installed, it has it's own move window ability.  LootRollMover may be overriden by the positioning that ElvUI has recorded in it's addon instead.

It's worth a look, I'm not 100% familiar with ElvUI.  But this thread has some pictures and info on the moving ability for windows and frames.
https://www.tukui.org/forum/viewtopic.php?t=7807

**Here are some pictures from that topic that may help.  **If this is STILL NOT the issue and LootRollMover is still broken**, then please let me know and I'll look into LootRollMover a bit more.**  Otherwise let me know if this helps so I can close this ticket.

![image](https://user-images.githubusercontent.com/202515/98444452-c469dc80-20df-11eb-9f99-277f46b6f6a5.png)

![image](https://user-images.githubusercontent.com/202515/98444454-c895fa00-20df-11eb-98b2-ae64c48f7bed.png)

![image](https://user-images.githubusercontent.com/202515/98444460-cc298100-20df-11eb-95fe-2b64c8e45f23.png)

![image](https://user-images.githubusercontent.com/202515/98444464-cfbd0800-20df-11eb-825b-5b40ed75bd44.png)

**Comment by Xruptor** [comment]
I haven't heard back in 4 days.  So I'm going to go ahead and close this ticket.
