### ISSUE TITLE
Loot roll window still doesn't appear

### ISSUE THREAD

**Issue by wheatbread** [Xruptor/LootRollMover#8]
Hi, thank you for your response!

Came back to report that unfortunately, it still doesn't show up in raid. 

-  When I type /lrm anchor, the anchor doesn't show up
- When loot drops for roll, I don't see the loot roll window
- Unloading the addon lets the window appear

**Comment by Xruptor** [comment]
Hmm really?  Can you tell me what country and what server you are playing on?  As well as what type? (Classic, Retail, etc..).  I was able to get the loot anchor to show so I need to see if it's something else going on that I'm missing.

**Comment by Xruptor** [comment]
![image](https://github.com/Xruptor/LootRollMover/assets/202515/465f06bf-adc4-409e-8248-205fa2af483c)

See? it works for me an I'm using the WOTLK PTR test server.  (I don't have a subscription so I have to test on PTR servers).
Have you tried disabling all addons and only LootRollMover?  Perhaps there is a conflict?  Regardless, make sure to answer my question above.

**Comment by wheatbread** [comment]
Hello,

It is on retail, on NA servers.    Ok, I'll test disabling everything except the addon when loot drops, when next I raid.

**Comment by Xruptor** [comment]
Hey there!  You don't have to wait for a raid.  If you say that the anchor doesn't even show when you type `/lrm anchor` you can test that without being in a raid.  With all your addons enabled, try using using `/lrm anchor`.  If the anchor window doesn't show, then try disabling all addons except LootRollMover.  Now type `/lrm anchor` and check.  If the anchor shows then another addon is conflicting or overwriting it.  If the anchor doesn't show then something else is going on.

If however the anchor works in both scenarios.  Then we can assume that something happens when loot is dropped.  In which case try disabling all addons except LRM when you do raid and test that as well.

**Comment by wheatbread** [comment]
Hi,

I tested it just now and disabled all addons except lootrollmover for the loot drop.  The loot roll window could not be seen.  I also typed in /lrm reset to try to reset the anchor and still did not see the loot window appear.

https://i.imgur.com/9tfF19s.png

**Comment by Xruptor** [comment]
> Hi,
> 
> I tested it just now and disabled all addons except lootrollmover for the loot drop. The loot roll window could not be seen. I also typed in /lrm reset to try to reset the anchor and still did not see the loot window appear.
> 
> https://i.imgur.com/9tfF19s.png

Did you try these things outside a raid?  You don't have to be in a raid or performing a raid/dungeon to move around the LRM anchor.  That is why I suggested to try it when you login.

I highly recommend you try this outside a raid and next time you login.  I'm completely baffled as to why it's not working for you.  It's an incredibly simple addon and considering the frame works for me, I just can't reproduce your issue.  It has to be something we are missing.  Are you absolutely SURE the addon is loaded?  Are you getting the command responses in your chatbox?  Does the addon show as loaded when you login?

What server, country and version of WOW are you playing on?  I really want this to work for you, but I need more details.

**Comment by Xruptor** [comment]
Never mind I think I was able to reproduce your error.  I'm assuming you tried to set the "scale" one time right?  Using the slider or manually increasing the frame scale?  I believe the frame scale is broken and is setting it down to zero.  That's why the frame isn't showing.  I'll see if I can fix it.

**Comment by Xruptor** [comment]
Since I hadn't heard back I'm assuming this was fixed for you.
